remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

logo: assets/images/UM_pb.png
title: Distributed Data Processing Environments
description: Bachelor in Data Science

github:
  is_project_page: false
